require("config.plugin_configs.lsp_config")
require("config.plugin_configs.colorscheme")
require("config.plugin_configs.completion")
require("config.plugin_configs.telescope")
require("config.plugin_configs.lualine")
require("config.plugin_configs.vim-svelte-plugin")
require("config.plugin_configs.neoformat")
